<?php
/**
 * Fontis MasterPass Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_MasterPass
 * @author     Matthew Gamble
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this Fontis_Masterpass_Block_Payment_Form */ ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none;">
    <li class="form-alt"><?php echo $this->__("You will be redirected to the %s website when you place an order.", Mage::helper("fontis_masterpass/config")->getFrontendTitle()); ?></li>
</ul>
