<?php
/**
 * Fontis MasterPass Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_MasterPass
 * @author     Matthew Gamble
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/** @var Fontis_Masterpass_Block_Checkout_Review_Details $this */
/** @var Mage_Tax_Helper_Data $taxHelper */
$taxHelper = Mage::helper("tax");
$displayBothPrices = $taxHelper->displayCartBothPrices();
if ($displayBothPrices) {
    $colspan = 2;
    $rowspan = 2;
} else {
    $colspan = 1;
    $rowspan = 1;
}
?>
<table id="details-table" class="data-table">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <?php if ($displayBothPrices): ?>
        <col width="1" />
        <col width="1" />
    <?php endif; ?>
    <thead>
    <tr>
        <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__("Product Name") ?></th>
        <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__("Price"); ?></th>
        <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__("Qty"); ?></th>
        <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__("Subtotal"); ?></th>
    </tr>
    <?php if ($displayBothPrices): ?>
        <tr>
            <th class="a-right"><?php echo $taxHelper->getIncExcTaxLabel(false); ?></th>
            <th><?php echo $taxHelper->getIncExcTaxLabel(true); ?></th>
            <th class="a-right"><?php echo $taxHelper->getIncExcTaxLabel(false); ?></th>
            <th><?php echo $taxHelper->getIncExcTaxLabel(true); ?></th>
        </tr>
    <?php endif; ?>
    </thead>
    <?php echo $this->getChildHtml("totals"); ?>
    <tbody>
    <?php foreach ($this->getItems() as $item): ?>
        <?php echo $this->getItemHtml($item); ?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable("details-table");</script>
