<?php
/**
 * Fontis MasterPass Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_MasterPass
 * @author     Matthew Gamble
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $this Fontis_Masterpass_Block_Checkoutlink */ ?>
<?php $translation = $this->__("Check out with %s", Mage::helper("fontis_masterpass/config")->getFrontendTitle()); ?>
<a href="<?php echo $this->getCheckoutUrl(); ?>" class="masterpass-checkoutlink"><img src="<?php echo $this->getImageUrl(); ?>" title="<?php echo $translation; ?>" alt="<?php echo $translation; ?>" /></a>
